name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_shell_escape: false

      - uses: actions/upload-artifact@v7
        with:
          name: plano-rp2
          path: main.pdf